# Generated by Django 2.2.4 on 2019-09-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AgriculturalLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=256)),
                ('type', models.IntegerField(choices=[(0, 'Grunt orny'), (1, 'Sad'), (2, 'Łąka trwała'), (3, 'Pastwisko trwałe')])),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_name', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=256)),
                ('expected_yield', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('comments', models.TextField(null=True)),
                ('land_plant', models.ManyToManyField(to='farmlife.AgriculturalLand')),
            ],
        ),
        migrations.CreateModel(
            name='AgriculturalMachinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinery_name', models.CharField(max_length=256)),
                ('fuel_consumption', models.IntegerField()),
                ('land_machinery', models.ManyToManyField(to='farmlife.AgriculturalLand')),
            ],
        ),
    ]
